config/routes.rb
Notes::Application.routes.draw do
  devise_for :users

  root :to => "notes#index"
  resources :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user

  attr_accessible :content, :title, :user_id

  after_initialize :init

  def init
    self.title ||= 'Untitled Note'
    self.content ||= 'Content'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @notes = current_user.notes
  end

  def new
    @note = current_user.notes.new
  end

  def create
    @note = current_user.notes.create(params[:note])

    respond_to do |format|
      format.json { render :json => @note.to_json }
    end
  end

  def edit
    @note = current_user.notes.find_by_id(params[:id])
  end

  def update
    @note = current_user.notes.find_by_id(params[:id])
    @note.update_attributes(params[:note])

    respond_to do |format|
      format.json { render :json => @note.to_json }
    end
  end

  def destroy
    @note = current_user.notes.find_by_id(params[:id])
    @note.destroy if @note.present?

    respond_to do |format|
      format.json { render :json => @note.to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notes</title>
  <link href='http://fonts.googleapis.com/css?family=Oxygen+Mono' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_edit_note.html.erb
<%= javascript_include_tag "mousetrap.js" %>
<%= javascript_include_tag "jquery.autosize.js" %>

<script type="text/javascript">
  var autosave_interval = null;
  var default_title = "Untitled Note";
  $(function() {
    set_content_spacing();

    $(".note_title_container").attr('contenteditable', 'true').focus();
    $(".note_title_container").on('keypress', function() {
      if (this.innerText.indexOf(default_title) !== 0) return;
      this.innerText = this.innerText.replace(default_title, "");
    });

    $(".note_content_container").click(function() {
      if (this.value.indexOf('Content') === 0) {
        this.value = this.value.replace(/^Content/, "");
      }
    });

    $(".editable_field").click(function(){
      $(this).attr('contentEditable', true);
      if (active_element && active_element.attr('class') !== $(this).attr('class')) {
        active_element.attr('contentEditable', false);
      }
      active_element = $(this);
    });

    Mousetrap.bind("command+s", function() {
      post_note_edits();

      return false;
    });

    autosave_interval = setInterval(function(){ post_note_edits() }, 60000); // autosave every minute
  });

  var active_element = null;
  var note_id = <%= @note.id.to_json %>;
  var currently_ajaxing = false;

  function post_note_edits() {
    if (!currently_ajaxing) {
      set_user_dialog('Saving...');
      currently_ajaxing = true;
      var note_title = $(".note_title_container").text();
      var note_content = $(".note_content_container").val().replace(/\n+$/, "\n");

      if (note_title === 'Untitled Note' && note_content === 'Content') {
        return;
      }

      if (note_id === null) {
        // first post of the note
        $.ajax({
          url: "/notes",
          method: "POST",
          dataType: "json",
          data: {
            note: {
              title: note_title,
              content: note_content
            }
          },
          success: function(new_note) {
            set_user_dialog('Saved');
            note_id = new_note.id;
            currently_ajaxing = false;
            clearInterval(autosave_interval);
            autosave_interval = setInterval(function(){ post_note_edits() }, 60000);
          }
        });
      } else {
        // make edits to an existing note
        $.ajax({
          url: "/notes/" + note_id,
          method: "put",
          dataType: "json",
          data: {
            note: {
              title: note_title,
              content: note_content
            }
          },
          success: function(note) {
            set_user_dialog('Saved');
            currently_ajaxing = false;
            clearInterval(autosave_interval);
            autosave_interval = setInterval(function(){ post_note_edits() }, 60000);
          }
        });
      }
    }
  }

  var message_id = 0;
  function set_user_dialog(message) {
    var this_message_id = ++message_id;
    $(".user_dialog .message").remove();
    $(".user_dialog").append("<span class='message user_dialog" + this_message_id + "'>" + message + "</span>");

    setTimeout(function() {
      $(".user_dialog" + this_message_id).fadeOut();
    }, 2000);
  }

  function set_content_spacing() {
    var window_height = $(window).height();
    var pixels_per_row = 25;

    var rows_to_add = Math.round((window_height / 2) / pixels_per_row);
    $(".note_content_container").autosize({append: "\n".repeat(rows_to_add)});

    // weird hack to get the autosizing with bottom padding correct
    setTimeout(function(){ $(".note_content_container").trigger("autosize.resize") }, 500);
  }
</script>

<%= render :partial => 'sidebar' %>

<div class='note_title_container editable_field'><%= @note.title %></div>
<textarea class='note_content_container'><%= @note.content %></textarea>
<div class='user_dialog'></div>

app/views/notes/_sidebar.html.erb
<div class='sidebar'>
  <div class='sidebar_item'>
    <a href='/' class='sidebar_home_item'><i class='icon-home'></i></a>
  </div>
  <div class='sidebar_item'>
    <a href='/notes/new' class='sidebar_new_item'><i class='icon-plus'></i></a>
  </div>
</div>

app/views/notes/edit.html.erb
<%= render :partial => 'edit_note' %>

app/views/notes/index.html.erb
<script type="text/javascript">
  $(function() {
    $(".delete_note").click(function() {
      var note_id = $(this).data('id');
      var $parent_node = $(this).parent();
      $.ajax({
        url: '/notes/' + note_id,
        method: 'DELETE',
        dataType: 'json',
        success: function() {
          $parent_node.remove();
        }
      })
    })
  });
</script>

<% if @notes.blank? %>
  <div class='note_summary_container'>You don't have any notes yet!</div>
<% end %>
<% @notes.each do |note| %>
  <div class='note_summary_container'>
    <span class='note_summary_title'><%= link_to note.title, edit_note_path(note.id) %></span>
    <span class='note_summary_content'><%= strip_tags note.content.truncate(180) %></span>
    <div class='delete_note' data-id='<%= note.id %>'><i class='icon-remove'></i></div>
  </div>
<% end %>
<%= link_to new_note_path, :class => 'new_note_button' do %>
  <i class='icon-plus'></i> New Note
<% end %>

app/views/notes/new.html.erb
<%= render :partial => 'edit_note' %>